[package]
name = "auto-save"
version = "0.0.1"
description = "Auto save for git."
license = "MIT"

[build]
target-dir = "Target"

[dependencies]
clap = "4.5.1"

[[bin]]
name = "Build"
path = "build.rs"
